# Generated by Django 5.1.6 on 2025-02-16 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='city_or_state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='home.cityorstate'),
            preserve_default=False,
        ),
    ]
